services:
  pl-active-container-runtime:
    image: prairielearn/prairielearn:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/course
      - ${HOME}/pl_ag_jobs:/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_JOBS_DIR=${HOME}/pl_ag_jobs
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - gdb-service

  gdb-service:
    build:
      context: ./gdb-image
      dockerfile: Dockerfile
    image: gdb-service:latest
